const button = document.getElementById('btn');
const output = document.querySelector('.output');

let quote=["I am pain free and totally in sync with life.",'I am grateful for my healthy body. I love life.','I attract success into my life','I find it easy to control my thoughts','I am grateful for every member of my family.','I nurture my blessed family with love and kindness, patience, and goodwill.','I am attracting money from all directions with my hard work.','I am entitled to financial freedom and carefree life.','I am thankful for the financial security I have and the way it makes me feel.','My inspired actions create ongoing prosperity.','Everywhere I go, I experience happiness in body, mind, and spirit.','Life supports me and new doors are opening for me all the time.','I am choosing to feel happy and positive energy is with me wherever I go.','I am always a happy-go-lucky kind of person.','Self-improvement is a habit that I nurture every day.','I am becoming the best version of myself.','I believe deeply that I can achieve anything I desire','I use positive thinking and beliefs to manifest a positive life','I choose a life filled with joy and happiness over one filled with anger and resentment.','I am aware of many components when making decisions','I know my wisdom and experiences guide me to the right decision.','Every day in every way I am becoming fitter and healthier.','I am becoming the best version of myself at the gym.','I love going to the gym.','I happily give and receive love each day.','I only think positively about love.','I allow love to find me easily and effortlessly','I only attract healthy, loving relationships.','Self-confidence is what I thrive on. Nothing is impossible and life is great.','I believe in myself.','I am always growing and developing.','When I breathe, I inhale confidence and exhale timidity and I am protected by God.','I am beautiful and alive.','The clothing I wear reflects my beauty and elegance.','I have a fit and attractive body and i am protected.','I am beauty and brains combined.','My hair are smooth and silky and very attractive','My skin is healthy and glowing and i am protected.','The universe is blessing me that enhance my beauty.','Every day is a perfect day for me and everything works out in my favour.','I love life and it loves me.','People see value in my services and I am rewarded graciously.','I am never alone in my pursuit of success. The universe supports me in expected and unexpected ways.','I am thankful for the wonderful nature around me and the chance to live in this incredible world.','I am thankful to the Universe for everything in my life.','I am thankful to my body for allowing me to live a healthy and zestful life.','I give thanks for the helpful spirits and ancestors that guide me in this life journey.',]
btn.addEventListener("click",()=>{
    let random =Math.floor(Math.random()*quote.length)
    output.textContent=quote[random]


})
